# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 363d601994d7610190e496ee5a6796dfacb15eddb85bfd7f4e5034ea935768ffaa878b2f10883a94c2e882f29c6568de398e2f3bdc7e488a4c10313e679cab67

test:
  secret_key_base: 1f11e3fe20f9b9e6343e78039299b1d33006a10b54d3cb431f5e07b9de05e9e3fd62bc5da7e050410dd8d286e683a076cdeebd918c9c45f5740b2113a1a2eba5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
